title: Blog - James Qin
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
#permalink: ':title/'
#baseurl: "/adam-blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings add your name
author: James Qin

author-pic: James.jpg
about-author: i am a automation engineer,now i want to work in it.

#修改成你自己的
# Contact links
website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
twitter: # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

#修改成你自己的
email: qinyu1@126.com
phone:
github:
jianshu:
juejin:
csdn:

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus修改成你自己的
discus_identifier: leach-chen
# Add your discus identifier

#intensedebate修改成你自己的
intensedebate_identifier:

# Tracker Google Analytics修改成你自己的
google-analysis:
baidu-analysis:

#youyan
youyan-id: 2157296

# Paginate
paginate: 18
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

imagepath: /blog

links:
  - name:         Home
    url:          https://qinyua.github.io
    external:     false
  - name:         About
    url:          /blog/about
    external:     false

#添加分类步骤：
#1：在_config.yml links1及blog_中添加对应内容
#2：在_includes里面headr.html中添加对应内容
#3：在根目录blog文件中创建对应内容

label1: <span style="font-size:12px">Publish by
label2:  </span>

links1:
  - name:         所有
    url:          /blog
    type:         recent
    external:     false
  - name:         随笔
    url:          /blog/myblog/essays
    type:         essays
    external:     false
  - name:         Jekyll
    url:          /blog/myblog/jekyll
    type:         jekyll
    external:     false
  - name:         Python
    url:          /blog/myblog/Python
    type:         Python
    external:     false
  - name:         Html5
    url:          /blog/myblog/Html5
    type:         Html5
    external:     false

blog_1:    recent
blog_2:    essays
blog_3:    jekyll
blog_4:    Python
blog_5:    Html5


permalink: /:year-:month-:day/:title.html

theme: jekyll-theme-slate